# Header
menu:
  主页: /
  所有文章: /archives
  随笔: /tags/随笔
  相册: photo

# SubNav
subnav:
  github: "https://github.com/WymanY"
  weibo: "http://weibo.com/u/2159267225/home?wvr=5&reason=&retcode="
  # rss: "#"
  # zhihu: "#"
  #douban: "#"
  # mail: "wuyun768@icloud.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: http://7xl8rl.com1.z0.glb.clouddn.com/blogPotrait.jpeg
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  kissGod的博客: http://www.jianshu.com/users/8d704c0faf00/latest_articles
  OneV's Den的博客: https://onevcat.com/
  南峰子的技术博客: http://kittenyang.com/
  杨萧玉HIT的博客: http://fish.yulingtianxia.com/
  objccn: http://www.objccn.io/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 记录一切美好的东西，在追求美好事物的道路上循序渐进
